name: task_management
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  date_picker_timeline: ^1.2.1
  device_info: ^1.0.0
  flutter_icons: ^1.1.0
  flutter_local_notifications: ^3.0.3
  flutter_staggered_animations: ^0.1.2
  flutter_svg: ^0.19.1
  get: ^3.24.0
  get_storage: ^1.4.0
  google_fonts: ^1.1.1
  sqflite: ^1.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg
